### ISSUE TITLE
Broken github link on desktop menu

### ISSUE THREAD

**Issue by pjfan** [labdao/labdao.xyz#26]
Github link on desktop menu links to https://www.githubLogo.com/labdao instead of https://www.github.com/labdao.

Fixed in PR below, let me know if this shoud be done differently (idk what established protocol for bug fixes is):
https://github.com/labdao/labdao.com/pull/25

**Comment by NiklasTR** [comment]
Thank you, Peter! Do you have an ETH address you could send me via discord? I would love to add you to our contributor graph.

**Comment by jlevers** [comment]
@NiklasTR pinging re above. just merged the PR
