### ISSUE TITLE
Replace "join our discord" with "start onboarding"

### ISSUE THREAD

**Issue by NiklasTR** [labdao/labdao.xyz#27]
<img width="297" alt="image" src="https://user-images.githubusercontent.com/18559148/172242961-49185533-18fd-49ee-8f17-6fe6ae5cb3d5.png">

website to link to: onboarding.labdao.xyz

let's also create a dedicated link for discord in the top bar. 

cc @lilyhg for this.

**Comment by jlevers** [comment]
fixed
